// <auto-generated />
using System;
using ChefEnCasa.Infrastructure.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChefEnCasa.Infraestructure.Migrations
{
    [DbContext(typeof(ChefEnCasaDbContext))]
    [Migration("20260515210228_AjusteLotesFEFO")]
    partial class AjusteLotesFEFO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Almacen", b =>
                {
                    b.Property<Guid>("AlmacenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadEnGramosOMl")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsPerecedero")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlmacenId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("UsuarioId", "IngredienteId", "FechaCaducidad")
                        .IsUnique()
                        .HasFilter("[FechaCaducidad] IS NOT NULL");

                    b.ToTable("ALMACENES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredienteId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("DiasVidaUtilEstimada")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEspanol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredienteId");

                    b.HasIndex("NombreEspanol")
                        .IsUnique();

                    b.ToTable("INGREDIENTES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.ListaCompra", b =>
                {
                    b.Property<int>("ListaCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaCompraId"));

                    b.Property<bool>("EstaCompletada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListaCompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LISTAS_COMPRAS", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.ListaCompraDetalle", b =>
                {
                    b.Property<int>("ListaCompraDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaCompraDetalleId"));

                    b.Property<decimal>("CantidadFaltante")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Comprado")
                        .HasColumnType("bit");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("ListaCompraId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedidaSugerida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListaCompraDetalleId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ListaCompraId");

                    b.ToTable("LISTA_COMPRA_DETALLES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.PerfilAlergia", b =>
                {
                    b.Property<int>("PerfilAlergiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilAlergiaId"));

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilSaludId")
                        .HasColumnType("int");

                    b.HasKey("PerfilAlergiaId");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("PerfilSaludId", "IngredienteId")
                        .IsUnique();

                    b.ToTable("PERFIL_ALERGIAS", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.PerfilSalud", b =>
                {
                    b.Property<int>("PerfilSaludId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilSaludId"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("EsCeliaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsVegano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsVegetariano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("IMC")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("IntoleranteLactosa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NecesidadCalorica")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TMB")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerfilSaludId")
                        .HasName("PK_PERFILESSALUD");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PERFILESSALUD", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaId"));

                    b.Property<int>("Calorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Carbohidratos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("EsSinGluten")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsSinLacteos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsVegano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsVegetariano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Grasas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porciones")
                        .HasColumnType("int");

                    b.Property<decimal>("Proteinas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpoonacularId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("RecetaId")
                        .HasName("PK_RECETAS");

                    b.HasIndex("Titulo");

                    b.ToTable("RECETAS", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.RecetaFavorita", b =>
                {
                    b.Property<int>("RecetaFavoritaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaFavoritaId"));

                    b.Property<DateTime>("FechaGuardado")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecetaFavoritaId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("UsuarioId", "RecetaId")
                        .IsUnique();

                    b.ToTable("RECETAS_FAVORITAS", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.Property<int>("RecetaIngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecetaIngredienteId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("CantidadEnGramosOMl")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RecetaIngredienteId")
                        .HasName("PK_RECETA_INGREDIENTES");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("RecetaId");

                    b.ToTable("RECETA_INGREDIENTES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Suscripcion", b =>
                {
                    b.Property<Guid>("SuscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstadoPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SuscripcionId")
                        .HasName("PK_SUSCRIPCIONES");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("SUSCRIPCIONES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaUltimaSesion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("PoliciesAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelefonoNumero")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TelefonoPrefijo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("TelefonoVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("UsuarioId")
                        .HasName("PK_USUARIOS");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Verificacion", b =>
                {
                    b.Property<int>("VerificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificacionId"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VerificacionId")
                        .HasName("PK_VERIFICACIONES");

                    b.ToTable("VERIFICACIONES", (string)null);
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Almacen", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefEnCasa.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.ListaCompra", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.ListaCompraDetalle", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefEnCasa.Domain.Entities.ListaCompra", "ListaCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("ListaCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("ListaCompra");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.PerfilAlergia", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefEnCasa.Domain.Entities.PerfilSalud", "PerfilSalud")
                        .WithMany("Alergias")
                        .HasForeignKey("PerfilSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("PerfilSalud");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.PerfilSalud", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilSalud")
                        .HasForeignKey("ChefEnCasa.Domain.Entities.PerfilSalud", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PERFILSALUD_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.RecetaFavorita", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChefEnCasa.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RECETA_INGREDIENTES_INGREDIENTE");

                    b.HasOne("ChefEnCasa.Domain.Entities.Receta", "Receta")
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RECETA_INGREDIENTES_RECETA");

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Suscripcion", b =>
                {
                    b.HasOne("ChefEnCasa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Suscripcion")
                        .HasForeignKey("ChefEnCasa.Domain.Entities.Suscripcion", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SUSCRIPCION_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.ListaCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.PerfilSalud", b =>
                {
                    b.Navigation("Alergias");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Receta", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("ChefEnCasa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilSalud")
                        .IsRequired();

                    b.Navigation("Suscripcion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
